import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MonthlyStatement } from '../types';
import { formatDate } from './formatters';

export function generateStatementPDF(statement: MonthlyStatement, type: 'vendor' | 'customer'): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleDateString('en-GB');

  doc.setFontSize(20);
  doc.setTextColor(21, 101, 192);
  doc.text('MilkPro', 14, 20);

  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);
  doc.text(type === 'vendor' ? 'Vendor Monthly Bill' : 'Customer Monthly Invoice', 14, 30);

  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text(`${type === 'vendor' ? 'Vendor' : 'Customer'}: ${statement.entityName}`, 14, 45);
  doc.text(`Period: ${statement.month} ${statement.year}`, 14, 53);
  doc.text(`Generated: ${today}`, pageWidth - 14 - doc.getTextWidth(`Generated: ${today}`), 45);

  doc.setDrawColor(200, 200, 200);
  doc.line(14, 58, pageWidth - 14, 58);

  autoTable(doc, {
    startY: 64,
    head: [['Date', 'Quantity (L)', 'Rate (PKR/L)', 'Amount (PKR)']],
    body: statement.transactions.map((t) => [
      formatDate(t.date),
      t.quantityLiters.toFixed(1),
      t.ratePerLiter.toFixed(2),
      t.amount.toFixed(2),
    ]),
    styles: { fontSize: 10, cellPadding: 4 },
    headStyles: { fillColor: [21, 101, 192], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [240, 244, 248] },
    foot: [
      ['TOTAL', statement.totalLiters.toFixed(1), `Avg: ${statement.averageRate.toFixed(2)}`, statement.totalAmount.toFixed(2)],
    ],
    footStyles: { fillColor: [230, 230, 230], textColor: [30, 30, 30], fontStyle: 'bold' },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 15;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');

  const summaryData = [
    [`Total Days: ${statement.totalDays}`, `Total Liters: ${statement.totalLiters.toFixed(1)} L`],
    [`Average Rate: PKR ${statement.averageRate.toFixed(2)}/L`, `Total Amount: PKR ${statement.totalAmount.toFixed(2)}`],
  ];

  autoTable(doc, {
    startY: finalY,
    body: summaryData,
    styles: { fontSize: 11, fontStyle: 'bold', cellPadding: 6 },
    theme: 'plain',
    columnStyles: { 0: { cellWidth: (pageWidth - 28) / 2 }, 1: { cellWidth: (pageWidth - 28) / 2 } },
  });

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by MilkPro - Milk Procurement & Distribution System', 14, doc.internal.pageSize.getHeight() - 10);

  const fileName = `${type === 'vendor' ? 'bill' : 'invoice'}_${statement.entityName.replace(/\s+/g, '_')}_${statement.month}_${statement.year}.pdf`;
  doc.save(fileName);
}
